import type { Dog, Breeder, ShowEvent, ShowResult, UserProfile } from "@shared/schema";

export const mockDogs: Dog[] = [
  {
    id: "dog-1",
    name: "Ares vom Adlerhorst",
    registrationNumber: "GSDCP-2021-0451",
    breed: "German Shepherd Dog",
    gender: "Male",
    dateOfBirth: "2021-03-15",
    color: "Black and Tan",
    imageUrl: "",
    owner: "Ahmed Khan",
    breeder: "Rashid Mehmood",
    sire: "Rex vom Haus Iris",
    dam: "Bella vom Adlerhorst",
    titles: ["V1", "SG", "BIS Puppy"],
    microchipNumber: "900118000123456",
  },
  {
    id: "dog-2",
    name: "Luna von der Stadtmitte",
    registrationNumber: "GSDCP-2020-0312",
    breed: "German Shepherd Dog",
    gender: "Female",
    dateOfBirth: "2020-07-22",
    color: "Sable",
    imageUrl: "",
    owner: "Faisal Iqbal",
    breeder: "Hassan Ali",
    sire: "Duke vom Nordberg",
    dam: "Zara von der Stadtmitte",
    titles: ["VA", "V1", "SchH3"],
  },
  {
    id: "dog-3",
    name: "Thor vom Eisenberg",
    registrationNumber: "GSDCP-2022-0587",
    breed: "German Shepherd Dog",
    gender: "Male",
    dateOfBirth: "2022-01-10",
    color: "Black and Red",
    imageUrl: "",
    owner: "Usman Tariq",
    breeder: "Khalid Hussain",
    sire: "Max vom Eisenberg",
    dam: "Sasha vom Goldental",
    titles: ["SG1"],
    microchipNumber: "900118000789012",
  },
  {
    id: "dog-4",
    name: "Freya vom Schwarzwald",
    registrationNumber: "GSDCP-2021-0423",
    breed: "German Shepherd Dog",
    gender: "Female",
    dateOfBirth: "2021-09-05",
    color: "Black and Tan",
    imageUrl: "",
    owner: "Bilal Ahmed",
    breeder: "Rashid Mehmood",
    sire: "Baron vom Schwarzwald",
    dam: "Heidi vom Bergland",
    titles: ["V1", "Best Female"],
  },
  {
    id: "dog-5",
    name: "Kaiser vom Rheintal",
    registrationNumber: "GSDCP-2019-0198",
    breed: "German Shepherd Dog",
    gender: "Male",
    dateOfBirth: "2019-11-30",
    color: "Bi-Color",
    imageUrl: "",
    owner: "Imran Malik",
    breeder: "Naveed Aslam",
    sire: "Zeus vom Rheintal",
    dam: "Nala vom Donauberg",
    titles: ["VA1", "BISS", "SchH3", "IPO3"],
    microchipNumber: "900118000345678",
  },
  {
    id: "dog-6",
    name: "Stella vom Goldental",
    registrationNumber: "GSDCP-2023-0634",
    breed: "German Shepherd Dog",
    gender: "Female",
    dateOfBirth: "2023-02-14",
    color: "Sable",
    imageUrl: "",
    owner: "Khalid Hussain",
    breeder: "Khalid Hussain",
    sire: "Thor vom Eisenberg",
    dam: "Luna von der Stadtmitte",
    titles: ["VP1"],
  },
];

export const mockBreeders: Breeder[] = [
  {
    id: "breeder-1",
    name: "Rashid Mehmood",
    kennelName: "vom Adlerhorst Kennels",
    location: "Lahore, Punjab",
    phone: "+92 300 1234567",
    email: "rashid@adlerhorst.pk",
    imageUrl: "",
    activeSince: "2008",
    totalDogs: 24,
    description: "Specializing in German show line German Shepherds with excellent temperament and conformation.",
  },
  {
    id: "breeder-2",
    name: "Hassan Ali",
    kennelName: "von der Stadtmitte",
    location: "Islamabad, ICT",
    phone: "+92 321 9876543",
    email: "hassan@stadtmitte.pk",
    imageUrl: "",
    activeSince: "2012",
    totalDogs: 18,
    description: "Breeding high-quality working line German Shepherds with proven pedigrees and health certifications.",
  },
  {
    id: "breeder-3",
    name: "Khalid Hussain",
    kennelName: "vom Eisenberg",
    location: "Karachi, Sindh",
    phone: "+92 333 4567890",
    email: "khalid@eisenberg.pk",
    imageUrl: "",
    activeSince: "2015",
    totalDogs: 12,
    description: "Focused on producing well-balanced German Shepherds suitable for both show and family life.",
  },
  {
    id: "breeder-4",
    name: "Naveed Aslam",
    kennelName: "vom Rheintal",
    location: "Rawalpindi, Punjab",
    phone: "+92 345 1122334",
    email: "naveed@rheintal.pk",
    imageUrl: "",
    activeSince: "2005",
    totalDogs: 32,
    description: "One of Pakistan's premier GSD breeders with multiple national and international champions.",
  },
  {
    id: "breeder-5",
    name: "Tariq Jameel",
    kennelName: "vom Bergland",
    location: "Faisalabad, Punjab",
    phone: "+92 312 5566778",
    email: "tariq@bergland.pk",
    imageUrl: "",
    activeSince: "2018",
    totalDogs: 8,
    description: "New generation breeder focusing on health-tested, well-socialized German Shepherds.",
  },
];

export const mockShowEvents: ShowEvent[] = [
  {
    id: "show-1",
    name: "GSDCP National Sieger Show 2025",
    date: "2025-03-15",
    location: "Lahore Gymkhana, Lahore",
    judge: "Herr Wolfgang Fischer (SV Germany)",
    status: "upcoming",
    entryCount: 85,
    description: "The premier annual conformation show of the German Shepherd Dog Club of Pakistan.",
  },
  {
    id: "show-2",
    name: "Punjab Regional Breed Survey",
    date: "2025-02-20",
    location: "Model Town Park, Lahore",
    judge: "Mr. Rashid Mehmood",
    status: "upcoming",
    entryCount: 42,
    description: "Regional breed survey and conformation evaluation for Punjab province.",
  },
  {
    id: "show-3",
    name: "Islamabad Capital Show 2025",
    date: "2025-04-10",
    location: "Fatima Jinnah Park, Islamabad",
    judge: "Dr. Amjad Hussain",
    status: "upcoming",
    entryCount: 38,
    description: "Capital territory specialty show with classes for all age groups.",
  },
  {
    id: "show-4",
    name: "GSDCP Winter Championship 2024",
    date: "2024-12-08",
    location: "Race Course Park, Lahore",
    judge: "Herr Klaus Schmidt (SV Germany)",
    status: "completed",
    entryCount: 72,
    description: "Winter championship show featuring top dogs from across Pakistan.",
  },
  {
    id: "show-5",
    name: "Karachi Open Show 2024",
    date: "2024-11-15",
    location: "Nisar Shaheed Park, Karachi",
    judge: "Mr. Naveed Aslam",
    status: "completed",
    entryCount: 55,
    description: "Open conformation show for all registered German Shepherds in Sindh region.",
  },
];

export const mockShowResults: ShowResult[] = [
  {
    id: "result-1",
    showEventId: "show-4",
    showName: "GSDCP Winter Championship 2024",
    dogId: "dog-5",
    dogName: "Kaiser vom Rheintal",
    handler: "Naveed Aslam",
    award: "VA1 (Excellent Select)",
    placement: 1,
    className: "Open Male",
    date: "2024-12-08",
  },
  {
    id: "result-2",
    showEventId: "show-4",
    showName: "GSDCP Winter Championship 2024",
    dogId: "dog-1",
    dogName: "Ares vom Adlerhorst",
    handler: "Ahmed Khan",
    award: "V1 (Excellent)",
    placement: 2,
    className: "Open Male",
    date: "2024-12-08",
  },
  {
    id: "result-3",
    showEventId: "show-4",
    showName: "GSDCP Winter Championship 2024",
    dogId: "dog-2",
    dogName: "Luna von der Stadtmitte",
    handler: "Faisal Iqbal",
    award: "VA1 (Excellent Select)",
    placement: 1,
    className: "Open Female",
    date: "2024-12-08",
  },
  {
    id: "result-4",
    showEventId: "show-4",
    showName: "GSDCP Winter Championship 2024",
    dogId: "dog-4",
    dogName: "Freya vom Schwarzwald",
    handler: "Bilal Ahmed",
    award: "V2 (Excellent)",
    placement: 2,
    className: "Open Female",
    date: "2024-12-08",
  },
  {
    id: "result-5",
    showEventId: "show-5",
    showName: "Karachi Open Show 2024",
    dogId: "dog-3",
    dogName: "Thor vom Eisenberg",
    handler: "Usman Tariq",
    award: "SG1 (Very Good)",
    placement: 1,
    className: "Young Male",
    date: "2024-11-15",
  },
  {
    id: "result-6",
    showEventId: "show-5",
    showName: "Karachi Open Show 2024",
    dogId: "dog-6",
    dogName: "Stella vom Goldental",
    handler: "Khalid Hussain",
    award: "VP1 (Very Promising)",
    placement: 1,
    className: "Puppy Female",
    date: "2024-11-15",
  },
  {
    id: "result-7",
    showEventId: "show-5",
    showName: "Karachi Open Show 2024",
    dogId: "dog-5",
    dogName: "Kaiser vom Rheintal",
    handler: "Imran Malik",
    award: "V1 (Excellent)",
    placement: 1,
    className: "Open Male",
    date: "2024-11-15",
  },
  {
    id: "result-8",
    showEventId: "show-4",
    showName: "GSDCP Winter Championship 2024",
    dogId: "dog-6",
    dogName: "Stella vom Goldental",
    handler: "Khalid Hussain",
    award: "VP1 (Very Promising)",
    placement: 1,
    className: "Puppy Female",
    date: "2024-12-08",
  },
];

export const mockUserProfile: UserProfile = {
  id: "user-1",
  name: "Ahmed Khan",
  email: "ahmed.khan@email.com",
  phone: "+92 300 1112233",
  membershipId: "GSDCP-M-2019-042",
  membershipStatus: "active",
  memberSince: "2019",
  imageUrl: "",
  city: "Lahore",
  dogIds: ["dog-1", "dog-4"],
};
